In [1]:
# numpy : 배열을 처리하기 쉽게 제공하는 모듈
import numpy as np

In [2]:
list_a = list(range(15))
print(type(list_a), list_a)

<class 'list'> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


In [3]:
arr = np.arange(15) # np.arange([start],stop,[step])
print(type(arr), arr)

# 차원 변경 : array.reshape(행, 열)
arr = arr.reshape(3,5)

print(arr.ndim)    # 차원 출력
print(arr.shape)  # 배열의 형태 ex)3,5
print(arr.size)
print(arr.dtype.name, arr.dtype.itemsize)
print(arr)

print(arr.reshape(arr.size)) # 평탄화

<class 'numpy.ndarray'> [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
2
(3, 5)
15
int32 4
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [4]:
import pandas as pd

df = pd.DataFrame(arr)
df

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14

In [5]:
# 리스트를 배열로 변경
arr_list1 = np.array(list_a)
print(arr_list1)

arr_list2 = np.array([[1,2,3],[4,5,6]])
print(arr_list2)

# 각 배열의 차원, 배열 형식, 전체 사이즈, 데이터 타입 출력

print()
print(arr_list1.ndim)    # 차원 출력
print(arr_list1.shape)  # 배열의 형태 ex)3,5
print(arr_list1.size)
print(arr_list1.dtype.name, arr_list1.dtype.itemsize)
print()
print(arr_list2.ndim)    # 차원 출력
print(arr_list2.shape)  # 배열의 형태 ex)3,5
print(arr_list2.size)
print(arr_list2.dtype.name, arr_list2.dtype.itemsize)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[1 2 3]
 [4 5 6]]

1
(15,)
15
int32 4

2
(2, 3)
6
int32 4


In [6]:
empty_arr = np.empty((3,4))
print(empty_arr)
print()
empty_arr = np.zeros((3,4))
print(empty_arr)
print()
empty_arr = np.zeros((3,4), dtype = 'i')   # 데이터 타입을 int로
print(empty_arr, empty_arr.dtype.itemsize)
print()
empty_arr = np.zeros((3,4), dtype = 'U4')   # 데이터 타입을 문자로
print(empty_arr)
print()
empty_arr = np.zeros((3,4), dtype = 'i8')   # 데이터 타입을 8바이트 int로
print(empty_arr, empty_arr.dtype.itemsize)
print()

# 데이터 초기값을 1로 주면서 배열 생성
empty_arr = np.ones((2,3))
print(empty_arr)
print()
empty_arr2 = np.zeros_like(empty_arr)
print(empty_arr2)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 2.33646336e-307]
 [7.56599807e-307 8.90104239e-307 1.24610383e-306 1.69118108e-306]
 [8.06632139e-308 1.20160711e-306 1.69119330e-306 1.33511018e-306]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 4

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 8

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
x1 = np.array([1.0, 2.0, 3.0])
y1 = np.array([5.0, 10.0, 15.0])
x2 = np.array([[1.0, 2.0],[ 3.0, 4.0]]) 
y2 = np.array([[5.0,10.0],[15.0,20.0]]) 
z1 = np.array([-1.0, -2.0])
z2 = np.array([[5.0],[10.0],[15.0]])

In [8]:
# array basic 연산
print(x1+y1)
print()
print(x2*y2)
print()
print(y2/z1)
print()
# array broadcast 연산
print(z1+z2)
print()
print(x1 ** 2)
print()
print(x1 < 3)

# shape
# x2 = np.array([[1.0, 2.0],[ 3.0, 4.0]])
print()
x2.reshape(x2.size)
print(x2)
y2.flatten() # 1차원으로 평탄화
print(y2)

x2.flatten().reshape(2,2)

[ 6. 12. 18.]

[[ 5. 20.]
 [45. 80.]]

[[ -5.  -5.]
 [-15. -10.]]

[[ 4.  3.]
 [ 9.  8.]
 [14. 13.]]

[1. 4. 9.]

[ True  True False]

[[1. 2.]
 [3. 4.]]
[[ 5. 10.]
 [15. 20.]]


array([[1., 2.],
       [3., 4.]])

In [9]:
# indexing, slicing, iterating
a = np.arange(10) ** 2
print(a)

# 3번째 자료 출력
print(a[2])

# 4부터 16까지 출력
print(a[2:5])

# 처음부터 끝까지 2씩 건너뛰어 출력
print(a[::2])

a[0:6:2] = -a[0:6:2]
print(a)

# 뒤에서부터 출력
print(a[::-1])

# for를 활용하여 값을 출력
for i in a:
    print(i, end = ' ')

[ 0  1  4  9 16 25 36 49 64 81]
4
[ 4  9 16]
[ 0  4 16 36 64]
[  0   1  -4   9 -16  25  36  49  64  81]
[ 81  64  49  36  25 -16   9  -4   1   0]
0 1 -4 9 -16 25 36 49 64 81 

In [10]:
# 배열을 검색
a = np.arange(1,21).reshape(4,5)
print(a)

#배열의 각 원소 검색 : array[행,열]
print(a[1,1])

print(a[:2,1])

# 마지막행과 마지막 열의 자료 출력
print(a[-1,-1])

# 2행의 모든 자료 검색
print(a[1,:])
# 3열의 모든 자료 검색
print(a[:,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
7
[2 7]
20
[ 6  7  8  9 10]
[ 3  8 13 18]


In [11]:
# np.ndarray(shape, buffer)
a = np.ndarray((3,2), buffer=np.arange(12))  # dtype = float
print(a)
a = np.ndarray((3,2), buffer=np.arange(6), dtype = int)
print(a)

[[2.12199579e-314 6.36598737e-314]
 [1.06099790e-313 1.48539705e-313]
 [1.90979621e-313 2.33419537e-313]]
[[0 1]
 [2 3]
 [4 5]]


In [68]:
a = np.array([[1,8,2],
              [3,2,5],
              [9,5,3]])
#            1) 1 8 2
#            2) 3 2 5
#            3) 9 5 3
print(np.argmax(a))
print(np.argmax(a,axis = 0))
print(np.argmax(a,axis = 1))
print()
b = np.array([[[1,2,333],[4,55,6],[7,88,9]],
              [[11,22,3],[44,555,66],[77,888,99]],
              [[111,222,33],[444,5,666],[777,88,999]]])

print(np.argmax(b))
print(np.argmax(b,axis = 0))
print(np.argmax(b,axis = 1))
print(np.argmax(b,axis = 2))

c = np.array([[[[1,2,3],[4,5,6],[7,8,9]],[[11,22,33],[44,55,66],[77,88,99]],[[111,222,333],[444,555,666],[777,888,999]],
              [[10,20,30],[40,50,60],[70,80,90]],[[110,220,330],[440,550,660],[770,880,990]],[[1110,2220,3330],[4440,5550,6660],[7770,8880,9990]],
              [[100,200,300],[400,500,600],[700,800,900]],[[1100,2200,3300],[4400,5500,6600],[7700,8800,9900]],[[11100,22200,33300],[44400,55500,66600],[77700,88800,99900]]]])

# print(np.argmax(c))
# print(np.argmax(c,axis = 0))
print("---------------------")
print(np.argmax(c,axis = 1))
# print("---------------------")
# print(np.argmax(c,axis = 2))
# print("---------------------")
# print(np.argmax(c,axis = 3))

6
[2 0 1]
[1 2 0]

26
[[2 2 0]
 [2 1 2]
 [2 1 2]]
[[2 2 0]
 [2 2 2]
 [2 0 2]]
[[2 1 1]
 [1 1 1]
 [1 2 2]]
---------------------
[[[8 8 8]
  [8 8 8]
  [8 8 8]]]


In [13]:
x = np.array([18, 5,10,23,19, -8, 10, 0, 0, 5, 2, 15, 8,
              2, 5, 4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13])
print(len(x))
print(x.min())
print(x.max())
print(x.mean())
print(x.std())
print(x.var())
print()
print(np.median(x), np.percentile(x,25), np.percentile(x,100))

26
-24
23
4.8076923076923075
10.734628476137871
115.23224852071006

5.0 0.0 23.0


In [22]:
# 난수 생성
# rand : 0부터 1사이의 정규분포로 난수 생성
# randn : 기대값이 0이고 표준편자가 1인 가우시안 표준 정규분포를 따르는 난수 생성

In [15]:
np.random.seed(10)      #난수 초기화 시드가 고정이면 난수 고정

print(np.random.randint(10,20,size=(2,5)))

[[19 14 10 11 19]
 [10 11 18 19 10]]


In [16]:
x = np.arange(10) # 0~9까지의 정수 발생, 1차원 배열
print(x)

# 자료의 위치를 바꿈

np.random.shuffle(x)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[1 5 2 9 7 0 3 4 6 8]


In [66]:
# 샘플링 함수 : choice 함수
# np.random.choice(data, size = None, replace = True, p = None)
print(np.random.choice(5,3))  # data = range(5), size = 3, 중복O
print(np.random.choice(5,5,replace = False))    # data = range(5), size = 5, 중복X
print(np.random.choice(5,10, p=[0.1,0.2,0.5,0.2,0]))    # 4는뽑지않고
                                                        #나머지 숫자의 확률을조정
print(np.random.choice(5,10, p=[1,0,0,0,0]))            # 0만 뽑겟다

[3 1 3]
[2 1 4 3 0]
[3 2 2 2 1 2 0 2 0 1]
[0 0 0 0 0 0 0 0 0 0]


In [90]:
# 1부터 20까지의 수를 가진 배열 생성
x = np.arange(1,21)
# 3의배수
print(x[x%3 ==0])
# 4로나누면 나머지가 1인수
print(x[x%4==1])
# 3으로 나누어지고 4로나누면 나머지가 1인 수
print(x[(x%3==0) & (x%4==1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]
