In [4]:
import numpy as np

a = np.arange(15).reshape(3,5)
print(a, type(a))
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype.name, a.dtype.itemsize)
a = np.arange(-5, 5, 0.5)
a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] <class 'numpy.ndarray'>
2
(3, 5)
15
int32 4


array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [23]:
a = np.array([1, 2, 3])
b = np.array([[1, 0],[ 3, 4]])
print(a, type(a))
print(b, type(b))
print(a.ndim, a.shape, a.size, a.dtype)
print(b.ndim, b.shape, b.size, b.dtype)


[1 2 3] <class 'numpy.ndarray'>
[[1 0]
 [3 4]] <class 'numpy.ndarray'>
1 (3,) 3 int32
2 (2, 2) 4 int32


In [19]:
a = np.zeros(5)
b = np.zeros((2, 3))
c = np.zeros((5, 2), dtype="i")
d = np.zeros(5, dtype="U4")
e = np.ones((2, 3, 4), dtype="i8")
f = np.ones_like(b, dtype="f")
g = np.empty((4, 3))

print(a, end = "\n\n")
print(b, end = "\n\n")
print(c, end = "\n\n")
print(d, end = "\n\n")
print(e, end = "\n\n")
print(f, end = "\n\n")
print(g, end = "\n\n")

[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]

['' '' '' '' '']

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[1.01855798e-312 1.06099790e-312 1.01855798e-312]
 [9.54898106e-313 1.03977794e-312 1.03977794e-312]
 [1.23075756e-312 1.03977794e-312 1.10343781e-312]
 [9.76118064e-313 1.14587773e-312 1.90979621e-312]]



In [21]:
print(e+e, end = "\n\n")
print(e-e, end = "\n\n")

[[[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]

 [[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]]

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]



In [37]:
a = np.array([1, 2, 3])

print(len(a))
print(np.mean(a))
print(np.var(a))
print(np.std(a))
print(np.max(a))
print(np.min(a))
print(np.median(a))
print(np.percentile(a,50))


3
2.0
0.6666666666666666
0.816496580927726
3
1
2.0
2.0


In [44]:
# 다음 행렬과 같은 배열이 있다.
# x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
# 이 배열에서 3의 배수를 찾아라.
# 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
# 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

print(x[x%3==0])
print(x[x%4==1])
print(x[(x%3==0)&(x%4==1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


In [50]:
# 다음 명령으로 타이타닉호 승객 데이터를 데이터프레임으로 읽어온다. 
# 이 명령을 실행하려면 seaborn 패키지가 설치되어 있어야 한다.
import seaborn as sns 
titanic = sns.load_dataset("titanic")

titanic
# 타이타닉호 승객 데이터의 데이터 값을 각 열마다 구해본다.


survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [58]:
import pandas as pd

print(titanic.tail())
print()
print(titanic.value_counts())
print()
# print(titanic.unique())
# print()
print(titanic.shape)
print()


     survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
890         0       3    male  32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

survived  pclass  sex     age   sibsp  parch  fare      embarked  class  who    adult_male  deck  embark_town  alive  alone
1         1       female  24.0  0      0      69.3000   C         First  wom

In [68]:
# seaborn 에서 titanic 데이터를 로드하여 데이터 프레임(titanic)으로 생성
# titanic 칼럼별 개수 확인
# titanic 전체 기본 정보 확인
# titanic 통계 정보 확인
# 칼럼별 개수가 200미만인 칼럼,
# 데이터 타입이 숫자가 아닌 칼럼은 제외하고 나머지 칼럼만 추출
# 데이터프레임(df) 생성
# df의 기본정보
# df 처음 5개의 정보
# df의 age와 fare칼럼에서 200번째부터 400번째까지 자료 추출하여 df_1에 저장
# df_1의 age 칼럼을 index칼럼으로

import seaborn as sns
import numpy as np

titanic = sns.load_dataset('titanic')

In [11]:
# titanic 칼럼별 개수 확인
titanic.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [10]:
# titanic 전체 기본 정보 확인
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [19]:
# titanic 통계 정보 확인
titanic.describe(include = 'all')

survived      pclass   sex         age       sibsp       parch  \
count   891.000000  891.000000   891  714.000000  891.000000  891.000000   
unique         NaN         NaN     2         NaN         NaN         NaN   
top            NaN         NaN  male         NaN         NaN         NaN   
freq           NaN         NaN   577         NaN         NaN         NaN   
mean      0.383838    2.308642   NaN   29.699118    0.523008    0.381594   
std       0.486592    0.836071   NaN   14.526497    1.102743    0.806057   
min       0.000000    1.000000   NaN    0.420000    0.000000    0.000000   
25%       0.000000    2.000000   NaN   20.125000    0.000000    0.000000   
50%       0.000000    3.000000   NaN   28.000000    0.000000    0.000000   
75%       1.000000    3.000000   NaN   38.000000    1.000000    0.000000   
max       1.000000    3.000000   NaN   80.000000    8.000000    6.000000   

              fare embarked  class  who adult_male deck  embark_town alive  \
count   891.000000      889    891  891        891  203          889   891   
unique         NaN        3      3    3          2    7            3     2   
top            NaN        S  Third  man       True    C  Southampton    no   
freq           NaN      644    491  537        537   59          644   549   
mean     32.204208      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
std      49.693429      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
min       0.000000      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
25%       7.910400      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
50%      14.454200      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
75%      31.000000      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
max     512.329200      NaN    NaN  NaN        NaN  NaN          NaN   NaN   

       alone  
count    891  
unique     2  
top     True  
freq     537  
mean     NaN  
std      NaN  
min      NaN  
25%      NaN  
50%      NaN  
75%      NaN  
max      NaN

In [109]:
# 칼럼별 개수가 300미만인 칼럼,
# 데이터 타입이 숫자가 아닌 칼럼은 제외하고 나머지 칼럼만 추출해서
# 데이터프레임(df) 생성
# titanic[titanic[titanic.count>300].dtype.isnumetic() == True]
cnt = titanic.count()[titanic.count()>=300].index
t_cnt = titanic[cnt]
num = t_cnt.dtypes[(t_cnt.dtypes == 'int64') | (t_cnt.dtypes == 'float64')].index
df = titanic[num]
df

survived  pclass   age  sibsp  parch     fare
0           0       3  22.0      1      0   7.2500
1           1       1  38.0      1      0  71.2833
2           1       3  26.0      0      0   7.9250
3           1       1  35.0      1      0  53.1000
4           0       3  35.0      0      0   8.0500
..        ...     ...   ...    ...    ...      ...
886         0       2  27.0      0      0  13.0000
887         1       1  19.0      0      0  30.0000
888         0       3   NaN      1      2  23.4500
889         1       1  26.0      0      0  30.0000
890         0       3  32.0      0      0   7.7500

[891 rows x 6 columns]

In [110]:
# df의 기본정보
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   age       714 non-null    float64
 3   sibsp     891 non-null    int64  
 4   parch     891 non-null    int64  
 5   fare      891 non-null    float64
dtypes: float64(2), int64(4)
memory usage: 41.9 KB


In [111]:
# df 처음 5개의 정보
df.head(5)

survived  pclass   age  sibsp  parch     fare
0         0       3  22.0      1      0   7.2500
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250
3         1       1  35.0      1      0  53.1000
4         0       3  35.0      0      0   8.0500

In [115]:
# df의 age와 fare칼럼에서 200번째부터 400번째까지 자료 추출하여 df_1에 저장
df_1 = df[200:401][['age', 'fare']]
df_1

age     fare
200  28.0   9.5000
201   NaN  69.5500
202  34.0   6.4958
203  45.5   7.2250
204  18.0   8.0500
..    ...      ...
396  31.0   7.8542
397  46.0  26.0000
398  23.0  10.5000
399  28.0  12.6500
400  39.0   7.9250

[201 rows x 2 columns]

In [119]:
# df_1의 age 칼럼을 index칼럼으로
df_1.rename(columns={"age":"index"})

index     fare
200   28.0   9.5000
201    NaN  69.5500
202   34.0   6.4958
203   45.5   7.2250
204   18.0   8.0500
..     ...      ...
396   31.0   7.8542
397   46.0  26.0000
398   23.0  10.5000
399   28.0  12.6500
400   39.0   7.9250

[201 rows x 2 columns]